database:
  uri: "mongodb+srv://db_username:db_password@db_cluster/db_name?retryWrites=true&w=majority"
  username: "root"
  password: "h0LqnbT3SrjVVSye"
  db_name: "task_management"
  max_pool_size: 50
  max_conn_idle_time: 36000
  retry_writes: true

server:
  port: 3000
  environment: "production"
  app_host: "0.0.0.0"
  app_domain: "localhost"

auth:
  jwt_secret: "prod_jwt_secret_key"
