// Code generated by "stringer -type=TaskStatus"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ToDo-0]
	_ = x[InProgress-1]
	_ = x[Done-2]
}

const _TaskStatus_name = "ToDoInProgressDone"

var _TaskStatus_index = [...]uint8{0, 4, 14, 18}

func (i TaskStatus) String() string {
	if i >= TaskStatus(len(_TaskStatus_index)-1) {
		return "TaskStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TaskStatus_name[_TaskStatus_index[i]:_TaskStatus_index[i+1]]
}
